### PR TITLE
Move to .Net 7

### PR DESCRIPTION
**Pull request by MamiyaOtaru**
use .net 7, newest Unknown6656.Core

# Updated the interpreter to the newest version of your core

There's some weirdness with needing 		<EnablePreviewFeatures>true</EnablePreviewFeatures>
and then 
<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
which causes some duplicate definitions in AssemblyInfo, been having to delete those as they get made, after which things compile.  

You may want to / be better qualified to clean up the .net dependencies etc but I think the update to the latest unknown6656.core should be helpful!

If this goes through, I've got a much smaller pull I can make that fixes a small bug so that ("1" = 1) is true as it should be in autoit

--------------------
- [ ] I hereby confirm that I have read through (and followed) the [contribution guide](https://github.com/Unknown6656/AutoIt-Interpreter/wiki/Contributing).

### CODE REVIEW

**Comment by Unknown6656** [comment]
Hey, thank you very much for your contribution and your interest in the project. Currently, I've got lots of open work on my plate, but I'll review your pull request as soon as possible. I know that I've got to migrate this project to the newest version, as well as clean-up `Unknown6656.Core`, which is quite a convoluted library.

**Comment by Unknown6656** [comment]
I've merged your commits using PR #158 and moved directly to .NET8. Next steps from my side:

1. fixing potential bugs during the next couple of days should I have introduced any
2. refactoring of existing code
3. set up more unit test
4. test your commits concerning type conversion

Thank you very much for your contributions!!!

**Comment by Unknown6656** [comment]
I tested your contributions superficially, and it seems to work. So thanks again! :)

image

**Comment by MamiyaOtaru** [comment]
Excellent news, be glad to pull your current version and work from there.  Thanks for keeping this running!

**Pull request closed without merging**
